apiVersion: apps/v1
kind: Deployment
metadata:
  name: kjgds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kjgds
  template:
    metadata:
      labels:
        app: kjgds
    spec:
      containers:
      - image: okteto.dev/kjgds:latest
        name: kjgds
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "3db33755-c497-4dd2-b278-3af9940d7be2"
        - name: Vless_Path
          value: "/yhfdr"
        - name: Vmess_UUID
          value: "f8bfb621-6728-4a6c-ae69-2106cd3d7c8a"
        - name: Vmess_Path
          value: "/mbcd"
        - name: Share_Path
          value: "/v2link"
